apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysqlrs1

spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      name: mysqlpod1
      labels:
         env: dev
    spec:
      containers:
      - name: "mysqlcon1"
        image: "mysql:5.6"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: redhat
        - name: MYSQL_DATABASE
          value: mydb
        - name: MYSQL_USER
          value: admin
        - name: MYSQL_PASSWORD
          value: admin






